baseURL: https://bhavyakapur.netlify.app/
languageCode: en-us
title: Welcome to my world!
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Get started to know more about my work
    title: Hi, my name is Bhavya
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: bkapur.mfa2022@london.edu
        title: Email address
    enable: yes
    phone:
      - phone: 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: London Business School
        text: ''
        url: https://www.london.edu
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/BhavyaKapur/
  image: ''
  name: Bhavya Kapur
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Analytics Mania
  tiles:
    enable: yes
    showcase:
      - image: delhi.jpeg
        subtitle: 
        title: My Journey
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Youth Risk Behavior Surveillance 
        url: blogs/magna
      - image: pic03.jpg
        subtitle: Differences between directors
        url: blogs/xyz
        title: IMDB ratings
      - image: Cryptocurrencies.jpg
        subtitle: 
        title: The Future of Cryptocurrencies
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
