baseURL: https://bhavyakapur.netlify.app/
languageCode: en-us
title: Welcome to my world!
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Get started to know more about my work
    title: Hi, my name is Bhavya Kapur!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: bkapur.mfa2022@london.edu
        title: Email address
    enable: yes
    #phone:
      #- phone: 
        title: 
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: London Business School
        text: ''
        url: https://www.london.edu
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/BhavyaKapur24/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/BhavyaKapur/
  image: ''
  name: Bhavya Kapur
  navigation:
    button1:
      - name: Get Started
        url: blogs
    # button2:
     # - name: Log In
     #   url: '#'
    links:
      - name: Home
        url: '#'
      # - name: Blogs
      #  url: blogs
   #   - name: Generic Blog
    #    url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    subtitle:
    title: Analytics Mania
  tiles:
    enable: yes
    showcase:
      - image: delhi.jpeg
        subtitle: 
        title: About me
        url: blogs/aliquam
      - image: youth.jpg
       # subtitle: 
        title: Youth Risk Behavior Surveillance 
        url: blogs/magna
      - image: pay gap.jpg
       # subtitle: 
        url: blogs/xyz
        title: Gender Pay Gap
      - image: cryptocurrencies.jpg
      #  subtitle: 
        title: Should you invest in Cryptocurrency? 
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "The website is a compilation of my work in Data Analytics and also includes a personal blog I wrote. To know more about my work, feel free to contact me on my social media handles."
    title: About My Work
    url: blogs
