---
title: "Omega Group plc- Pay Discrimination"
description: 
date: '2017-10-31T22:26:09-05:00'
image: pay gap.jpg
keywords: ''
slug: xyz
draft: no
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635~
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma~
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3~</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals . Hypothesis testing . Correlation analysis . Regression</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data=omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Summary Statistics of salary by gender
df&lt;-mosaic::favstats (salary ~ gender, data=omega)
df</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 

df_01&lt;-select(df,gender,mean,sd,n)

# the t-critical value, the standard error, the margin of error, 

df_02 &lt;- df_01 %&gt;% 
  mutate(t_critical = qt(0.975, n-1),
         SE = sd / sqrt(n),
         margin_error = SE * t_critical)
df_02</code></pre>
<pre><code>##   gender  mean   sd  n t_critical   SE margin_error
## 1 female 64543 7567 26       2.06 1484         3056
## 2   male 73239 7463 24       2.07 1523         3151</code></pre>
<pre class="r"><code># and the low/high endpoints of a 95% condifence interval

df_03 &lt;- df_02 %&gt;% 
  mutate(high_end = mean + margin_error,
         low_end = mean - margin_error)
df_03</code></pre>
<pre><code>##   gender  mean   sd  n t_critical   SE margin_error high_end low_end
## 1 female 64543 7567 26       2.06 1484         3056    67599   61486
## 2   male 73239 7463 24       2.07 1523         3151    76390   70088</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>There seems to be a significant difference between female and male salaries. In fact, while the confidence interval for females’ salaries goes from 61,486 to 67,599, the one for men goes from 70,088 to 76,390. In other words, the two CIs do not overlap, something that suggests us to directly reject the null hypothesis that the two means are equal.</p>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using t.test() 

t.test(salary~gender,data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code>glimpse(omega)</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635~
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma~
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3~</code></pre>
<pre class="r"><code># hypothesis testing using infer package

 diff_salary &lt;- omega %&gt;%
   specify(salary ~ gender) %&gt;%
   hypothesize(null = &quot;independence&quot;) %&gt;%
   generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
   calculate(stat =&quot;diff in means&quot;,
             order=c(&quot;male&quot;,&quot;female&quot;))
 diff_salary %&gt;% 
   visualize()</code></pre>
<p><img src="/blogs/pay_files/figure-html/hypothesis_testing-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>First of all, since the p value is lower than 0.05, we reject the null hypothesis at a 95% confidence level. In other words, we can say that there is a statistically significant difference between the means man and female salaries.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of experience by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<pre class="r"><code># Summary Statistics of experience by gender
df&lt;-mosaic::favstats (experience ~ gender, data=omega)
df</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 

df_05&lt;-select(df,gender,mean,sd,n)

# the t-critical value, the standard error, the margin of error, 

df_06&lt;-df_05 %&gt;% 
  mutate(t_critical=qt(0.975,n-1),
         SE=sd/sqrt(n),
         margin_error=SE*t_critical)
df_06</code></pre>
<pre><code>##   gender  mean    sd  n t_critical   SE margin_error
## 1 female  7.38  8.51 26       2.06 1.67         3.44
## 2   male 21.12 10.92 24       2.07 2.23         4.61</code></pre>
<pre class="r"><code># and the low/high endpoints of a 95% condifence interval

df_07&lt;-df_06 %&gt;% 
  mutate(high_end=mean+margin_error,
         low_end=mean-margin_error)
df_07</code></pre>
<pre><code>##   gender  mean    sd  n t_critical   SE margin_error high_end low_end
## 1 female  7.38  8.51 26       2.06 1.67         3.44     10.8    3.95
## 2   male 21.12 10.92 24       2.07 2.23         4.61     25.7   16.52</code></pre>
<pre class="r"><code># hypothesis testing using t.test() 

t.test(experience~gender,data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code>glimpse(omega)</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635~
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma~
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3~</code></pre>
<pre class="r"><code># hypothesis testing using infer package

 diff_experience &lt;- omega %&gt;%
   specify(experience ~ gender) %&gt;%
   hypothesize(null = &quot;independence&quot;) %&gt;%
   generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
   calculate(stat =&quot;diff in means&quot;,
             order=c(&quot;male&quot;,&quot;female&quot;))
 diff_experience %&gt;% 
   visualize()</code></pre>
<p><img src="/blogs/pay_files/figure-html/unnamed-chunk-1-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>At any reasonable significance level we can reject the H0 in favour of H1 - there is a significant difference between the experience of executives of different gender. This can be an explanation for salary difference.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>omega %&gt;% 
ggplot(aes(x = experience, y = salary, color = gender))+
  geom_point() +
  geom_smooth(alpha=0.3) +
  theme_bw() +
  labs(x = &quot;Experience, Years&quot;,
       y = &quot;Salary&quot;,
       title = &quot;Relationship between experience and salary&quot;) +
  theme(legend.position = &quot;none&quot;) +
  facet_wrap(~ gender, scales = &quot;free&quot;)</code></pre>
<p><img src="/blogs/pay_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes (colour = gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/pay_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
<p>From the plot we can infer that salary and experience are positively correlated. In fact, salary increases as experience increases. We can also infer that salary variability is highest in the first years of experiences, then it decreases when experiences in between 1 and 15 years, and then it increases again for employees with several years of experience.</p>
</div>
